### ISSUE TITLE
Chapter 0: running a custom node

### ISSUE THREAD

**Issue by invis87** [substrate-developer-hub/substrate-collectables-workshop#116]
here: https://substrate.dev/substrate-collectables-workshop/#/0/running-a-custom-node
you say `Then let's go into the now renamed substratekitties folder and build our pre-configured node:`, but `./scripts/build.sh` return error:
```
error[E0432]: unresolved import `substratekitties_runtime`
 --> src/lib.rs:5:9
  |
5 | pub use substratekitties_runtime::*;
  |         ^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared type or module `substratekitties_runtime`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `node-template-runtime-wasm`.
```

**Comment by elliotweaver** [comment]
I just ran into this as well.

**Comment by shawntabrizi** [comment]
The problem probably has to do with an update of my script.

Search your project for "node-template" and replace it with `substratekitties`

Will fix soon

**Comment by shawntabrizi** [comment]
I think this fixed it, please reopen and ping me if that is not the case. Sorry!
https://github.com/shawntabrizi/substrate-package/commit/ba8590ee5edc24ec77e63ef5fc1f50fb4f473cc1

**Comment by shawntabrizi** [comment]
https://github.com/shawntabrizi/substrate-package/commit/ed1228f49ab2e1db152417096848abe4f4afd72a
