### ISSUE TITLE
Kitties are breedable without owners' consent

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-collectables-workshop#117]
The [`breed_kitty` function](https://github.com/substrate-developer-hub/substrate-collectables-workshop/blob/master/3/assets/3.5-finished-code.rs#L138) does not ensure that the owners of the kitties are interested in breeding.

An attacker could breed two strangers' kitties and keep the offspring.

**Comment by shawntabrizi** [comment]
To me, this authorization check adds complexity where it is otherwise not very educational.

**Comment by JoshOrndorff** [comment]
Good point. This is for teaching, not for production.

**Comment by todofixthis** [comment]
This was added as a stretch goal in https://substrate.dev/substrate-collectables-workshop/#/3/playing-our-game
