### ISSUE TITLE
Outdated documentation link

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-collectables-workshop#118]
At the bottom of the left sidebar there is a link titled "Documentation" that points to docs.substrate.dev/docs

At minimum the url should be updated, but perhaps the anchor text should also be changed to something like "Substrate developer hub" or "More substrate docs"

**Comment by soc1c** [comment]
yeah, getting the same. some domain moved apparently.

**Comment by shawntabrizi** [comment]
fixed in #123
