### ISSUE TITLE
"Next" link in english welcome page links to chinese page

### ISSUE THREAD

**Issue by bddap** [substrate-developer-hub/substrate-collectables-workshop#120]
To reproduce:

- Go to https://substrate.dev/substrate-collectables-workshop/#/README
- Click next at the bottom of the page, directs to chinese welcome page
- Click next again, redirects to japanese

Ideally, the "next" button would link to https://substrate.dev/substrate-collectables-workshop/#/0/introduction instread.

**Comment by shawntabrizi** [comment]
Nice catch
