### ISSUE TITLE
The Chinese translation are not in sync.

### ISSUE THREAD

**Issue by kaichaosun** [substrate-developer-hub/substrate-collectables-workshop#134]
There are Chinese translations for this tutorial, but they are both not in sync with the English version, the contents which are not translated include:
* Chapter 5
* Chapter Extra

**Comment by shawntabrizi** [comment]
I would not encourage over-investing on adding these new chapters because we will come out with a v2 of the guide soon.

Creating this content is still partially useful for people who want to look at the past and use v1.
