### ISSUE TITLE
Error: no `with_storage`, `StorageOverlay`, or `ChildrenStorageOverlay` in the root

### ISSUE THREAD

**Issue by ltfschoen** [substrate-developer-hub/substrate-collectables-workshop#147]
After following the step to "Add Extra Genesis" in https://substrate.dev/substrate-collectables-workshop/#/5/testing-genesis?id=add-extra-genesis, when I compile my runtime with `./scripts/build.sh` I get the following errors that tell me that `with_storage`, `StorageOverlay` and `ChildrenStorageOverlay` are not in the root

```
error[E0432]: unresolved imports `runtime_io::with_storage`, `runtime_io::StorageOverlay`, `runtime_io::ChildrenStorageOverlay`
 --> /Users/ls/node/runtime/src/network.rs:7:18
  |
7 | use runtime_io::{with_storage, StorageOverlay, ChildrenStorageOverlay};
  |                  ^^^^^^^^^^^^  ^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^ no `ChildrenStorageOverlay` in the root
  |                  |             |
  |                  |             no `StorageOverlay` in the root
  |                  no `with_storage` in the root
  |                  help: a similar name exists in the module: `set_storage`
```

**Comment by bkchr** [comment]
You don't need `with_storage` anymore, that is done automatically for you.

**Comment by ltfschoen** [comment]
Thank you! Yes, it appears the more recent technique is described in the [TCR tutorial](https://substrate.dev/docs/en/tutorials/tcr/)
