### ISSUE TITLE
# not // in bash

### ISSUE THREAD

**Issue by drandreaskrueger** [substrate-developer-hub/substrate-collectables-workshop#148]
this is so tiny, I am almost embarassed to report it, but

    ./scripts/build.sh       # Build Wasm
    cargo build --release    # Build binary

not

    ./scripts/build.sh               // Build Wasm
    cargo build --release    // Build binary

on

https://substrate.dev/substrate-collectables-workshop/#/0/common-patterns-moving-forward

**Comment by riusricardo** [comment]
Thanks, I'll push a fix on the next PR.
