### ISSUE TITLE
"runtime.substratekitties" is undefined in the console

### ISSUE THREAD

**Issue by mitsu1124** [substrate-developer-hub/substrate-collectables-workshop#150]
Now I'm on the below page in tutorial.

https://substrate.dev/substrate-collectables-workshop/#/4/explore

When I type in "runtime." in the console, substratekitties doesn't show up.

![image](https://user-images.githubusercontent.com/45583595/69926612-6f4d4000-14f8-11ea-8ba9-6228d6085fc3.png)

It's just my guess but I got an error with blake2 module when I "yarn install" at ~/substrate/substrate-package/substratekitties-ui.

Pleasure if someone could help me.

Device: MacBook Air
OS: High Sierra

---

Mitsu@sumire-no-MacBook-Air:~/coding/substrate/substrate-package/substratekitties-ui$ yarn install
yarn install v1.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @polkadot/wasm-crypto@0.3.1" has unmet peer dependency "@polkadot/util@*".
[4/4] 🔨  Building fresh packages...
[-/4] ⠄ waiting...
[2/4] ⠄ blake2js
[-/4] ⠄ waiting...
error /Users/Mitsu/coding/substrate/substrate-package/substratekitties-ui/node_modules/blake2js: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/Mitsu/coding/substrate/substrate-package/substratekitties-ui/node_modules/blake2js
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@12.12.0 | darwin | x64
gyp info find Python using Python version 2.7.10 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/Cellar/node/12.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Mitsu/coding/substrate/substrate-package/substratekitties-ui/node_modules/blake2js/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/12.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Mitsu/Library/Caches/node-gyp/12.12.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/12.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/Mitsu/Library/Caches/node-gyp/12.12.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/Mitsu/coding/substrate/substrate-package/substratekitties-ui/node_modules/blake2js',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/addon/lib/BLAKE2/sse/blake2s.o
../lib/BLAKE2/sse/blake2s.c:48:22: warning: unused variable 'blake2s_sigma' [-Wunused-const-variable]
static const uint8_t blake2s_sigma[10][16] =
                     ^
../lib/BLAKE2/sse/blake2s.c:89:26: warning: unused function 'blake2s_clear_lastblock' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2s_clear_lastblock( blake2s_state *S )
                         ^
../lib/BLAKE2/sse/blake2s.c:108:26: warning: unused function 'blake2s_param_set_digest_length' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2s_param_set_digest_length( blake2s_param *P, const uint8_t digest_length )
                         ^
../lib/BLAKE2/sse/blake2s.c:114:26: warning: unused function 'blake2s_param_set_fanout' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2s_param_set_fanout( blake2s_param *P, const uint8_t fanout )
                         ^
../lib/BLAKE2/sse/blake2s.c:120:26: warning: unused function 'blake2s_param_set_max_depth' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2s_param_set_max_depth( blake2s_param *P, const uint8_t depth )
                         ^
../lib/BLAKE2/sse/blake2s.c:126:26: warning: unused function 'blake2s_param_set_leaf_length' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2s_param_set_leaf_length( blake2s_param *P, const uint32_t leaf_length )
                         ^
../lib/BLAKE2/sse/blake2s.c:132:26: warning: unused function 'blake2s_param_set_node_offset' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2s_param_set_node_offset( blake2s_param *P, const uint64_t node_offset )
                         ^
../lib/BLAKE2/sse/blake2s.c:138:26: warning: unused function 'blake2s_param_set_node_depth' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2s_param_set_node_depth( blake2s_param *P, const uint8_t node_depth )
                         ^
../lib/BLAKE2/sse/blake2s.c:144:26: warning: unused function 'blake2s_param_set_inner_length' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2s_param_set_inner_length( blake2s_param *P, const uint8_t inner_length )
                         ^
../lib/BLAKE2/sse/blake2s.c:150:26: warning: unused function 'blake2s_param_set_salt' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2s_param_set_salt( blake2s_param *P, const uint8_t salt[BLAKE2S_SALTBYTES] )
                         ^
../lib/BLAKE2/sse/blake2s.c:156:26: warning: unused function 'blake2s_param_set_personal' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2s_param_set_personal( blake2s_param *P, const uint8_t personal[BLAKE2S_PERSONALBYTES] )
                         ^
../lib/BLAKE2/sse/blake2s.c:162:26: warning: unused function 'blake2s_init0' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2s_init0( blake2s_state *S )
                         ^
12 warnings generated.
  CC(target) Release/obj.target/addon/lib/BLAKE2/sse/blake2sp.o
  CC(target) Release/obj.target/addon/lib/BLAKE2/sse/blake2b.o
../lib/BLAKE2/sse/blake2b.c:52:22: warning: unused variable 'blake2b_sigma' [-Wunused-const-variable]
static const uint8_t blake2b_sigma[12][16] =
                     ^
../lib/BLAKE2/sse/blake2b.c:95:26: warning: unused function 'blake2b_clear_lastblock' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2b_clear_lastblock( blake2b_state *S )
                         ^
../lib/BLAKE2/sse/blake2b.c:121:26: warning: unused function 'blake2b_param_set_digest_length' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2b_param_set_digest_length( blake2b_param *P, const uint8_t digest_length )
                         ^
../lib/BLAKE2/sse/blake2b.c:127:26: warning: unused function 'blake2b_param_set_fanout' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2b_param_set_fanout( blake2b_param *P, const uint8_t fanout )
                         ^
../lib/BLAKE2/sse/blake2b.c:133:26: warning: unused function 'blake2b_param_set_max_depth' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2b_param_set_max_depth( blake2b_param *P, const uint8_t depth )
                         ^
../lib/BLAKE2/sse/blake2b.c:139:26: warning: unused function 'blake2b_param_set_leaf_length' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2b_param_set_leaf_length( blake2b_param *P, const uint32_t leaf_length )
                         ^
../lib/BLAKE2/sse/blake2b.c:145:26: warning: unused function 'blake2b_param_set_node_offset' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2b_param_set_node_offset( blake2b_param *P, const uint64_t node_offset )
                         ^
../lib/BLAKE2/sse/blake2b.c:151:26: warning: unused function 'blake2b_param_set_node_depth' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2b_param_set_node_depth( blake2b_param *P, const uint8_t node_depth )
                         ^
../lib/BLAKE2/sse/blake2b.c:157:26: warning: unused function 'blake2b_param_set_inner_length' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2b_param_set_inner_length( blake2b_param *P, const uint8_t inner_length )
                         ^
../lib/BLAKE2/sse/blake2b.c:163:26: warning: unused function 'blake2b_param_set_salt' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2b_param_set_salt( blake2b_param *P, const uint8_t salt[BLAKE2B_SALTBYTES] )
                         ^
../lib/BLAKE2/sse/blake2b.c:169:26: warning: unused function 'blake2b_param_set_personal' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2b_param_set_personal( blake2b_param *P, const uint8_t personal[BLAKE2B_PERSONALBYTES] )
                         ^
../lib/BLAKE2/sse/blake2b.c:175:26: warning: unused function 'blake2b_init0' [-Wunused-function]
BLAKE2_LOCAL_INLINE(int) blake2b_init0( blake2b_state *S )
                         ^
12 warnings generated.
  CC(target) Release/obj.target/addon/lib/BLAKE2/sse/blake2bp.o
  CXX(target) Release/obj.target/addon/src/addon.o
../src/addon.cc:12:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        exports->Set(New("blake2s").ToLocalChecked(), blake2s());
                 ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/addon.cc:13:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        exports->Set(New("blake2sp").ToLocalChecked(), blake2sp());
                 ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/addon.cc:14:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        exports->Set(New("blake2b").ToLocalChecked(), blake2b());
                 ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/addon.cc:15:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        exports->Set(New("blake2bp").ToLocalChecked(), blake2bp());
                 ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
4 warnings generated.
  CXX(target) Release/obj.target/addon/src/blake2.o
In file included from ../src/blake2.cc:2:
../src/utils.hh:37:36: error: too few arguments to function call, single argument 'context' was not specified
        uint32_t value = obj->Uint32Value();
                         ~~~~~~~~~~~~~~~~ ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:2611:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:65:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("BUFFER_SIZE").ToLocalChecked(), New<Number>(sizeof(blake2_state)));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:66:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("BLOCKBYTES").ToLocalChecked(), New<Number>(BLOCKBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:67:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("OUTBYTES").ToLocalChecked(), New<Number>(OUTBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:68:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("KEYBYTES").ToLocalChecked(), New<Number>(KEYBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:69:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("PERSONALBYTES").ToLocalChecked(), New<Number>(PERSONALBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:65:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("BUFFER_SIZE").ToLocalChecked(), New<Number>(sizeof(blake2_state)));
             ^
../src/blake2.cc:15:16: note: in instantiation of function template specialization 'B2JS::Utils::Wrap<__blake2s_state, &blake2s_init, &blake2s_init_key, &blake2s_update, &blake2s_final, 64, 32, 32, 8, 8>' requested here
        return Utils::Wrap<
                      ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:66:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("BLOCKBYTES").ToLocalChecked(), New<Number>(BLOCKBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:67:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("OUTBYTES").ToLocalChecked(), New<Number>(OUTBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:68:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("KEYBYTES").ToLocalChecked(), New<Number>(KEYBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:69:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("PERSONALBYTES").ToLocalChecked(), New<Number>(PERSONALBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:65:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("BUFFER_SIZE").ToLocalChecked(), New<Number>(sizeof(blake2_state)));
             ^
../src/blake2.cc:32:16: note: in instantiation of function template specialization 'B2JS::Utils::Wrap<__blake2sp_state, &blake2sp_init, &blake2sp_init_key, &blake2sp_update, &blake2sp_final, 64, 32, 32, 8, 8>' requested here
        return Utils::Wrap<
                      ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:66:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("BLOCKBYTES").ToLocalChecked(), New<Number>(BLOCKBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:67:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("OUTBYTES").ToLocalChecked(), New<Number>(OUTBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:68:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("KEYBYTES").ToLocalChecked(), New<Number>(KEYBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:69:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("PERSONALBYTES").ToLocalChecked(), New<Number>(PERSONALBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:65:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("BUFFER_SIZE").ToLocalChecked(), New<Number>(sizeof(blake2_state)));
             ^
../src/blake2.cc:49:16: note: in instantiation of function template specialization 'B2JS::Utils::Wrap<__blake2b_state, &blake2b_init, &blake2b_init_key, &blake2b_update, &blake2b_final, 128, 64, 64, 16, 16>' requested here
        return Utils::Wrap<
                      ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:66:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("BLOCKBYTES").ToLocalChecked(), New<Number>(BLOCKBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:67:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("OUTBYTES").ToLocalChecked(), New<Number>(OUTBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:68:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("KEYBYTES").ToLocalChecked(), New<Number>(KEYBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:69:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("PERSONALBYTES").ToLocalChecked(), New<Number>(PERSONALBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:65:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("BUFFER_SIZE").ToLocalChecked(), New<Number>(sizeof(blake2_state)));
             ^
../src/blake2.cc:66:16: note: in instantiation of function template specialization 'B2JS::Utils::Wrap<__blake2bp_state, &blake2bp_init, &blake2bp_init_key, &blake2bp_update, &blake2bp_final, 128, 64, 64, 16, 16>' requested here
        return Utils::Wrap<
                      ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:66:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("BLOCKBYTES").ToLocalChecked(), New<Number>(BLOCKBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:67:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("OUTBYTES").ToLocalChecked(), New<Number>(OUTBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:68:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("KEYBYTES").ToLocalChecked(), New<Number>(KEYBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/blake2.cc:2:
../src/utils.hh:69:7: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        obj->Set(New<String>("PERSONALBYTES").ToLocalChecked(), New<Number>(PERSONALBYTES));
             ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/Mitsu/Library/Caches/node-gyp/12.12.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
25 warnings and 1 error generated.
make: *** [Release/obj.target/addon/src/blake2.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/12.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/12.12.0/bin/node" "/usr/local/Cellar/node/12.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Mitsu/coding/substrate/substrate-package/substratekitties-ui/node_modules/blake2js
gyp ERR! node -v v12.12.0

**Comment by shawntabrizi** [comment]
It looks like your UI is not connected to your node. Are you running a node while trying to connect via the UI?

**Comment by mitsu1124** [comment]
@shawntabrizi 
Shawn, thanks for your reply. Yes, I forgot to run a node while starting the UI. It has shown up like below. Appreciated for your response.

![image](https://user-images.githubusercontent.com/45583595/70095972-59ab5800-1669-11ea-8fad-cbba906340ad.png)
